### PR TITLE
Creating French help page

### PR DESCRIPTION
**Pull request by goofy-bz**

### CODE REVIEW

**Comment by kaepora** [comment]
Thanks a lot for this, but please do not translate anything else for now. I do not want to maintain French translations beyond the bare necessities (home and help pages). I will review this soon.

**Comment by goofy-bz** [comment]
> I do not want to maintain French translations beyond the bare necessities (home and help pages)
Sure, I understand. Anyway I can maintain these two French pages when needed.

**Comment by kaepora** [comment]
@goofy-bz That's exactly the problem. I don't want to have parts of the project that I can't maintain myself. I'm only accepting your additional French translations because I'm fluent in French.

**Comment by goofy-bz** [comment]
allright, don't worry I won't interfere any longer :)

**Pull request closed without merging**
